# -*- coding: utf-8 -*-
"""Machine learning Nominas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq3X6eagB3fMfcfNtCKWeC76an-yL2wz

Proyecto: Inferencia de Ingresos usando Machine Learning
Estudiante: (Tu nombre)
Profesor: Carlos Ogando

Descripción:
Este proyecto tiene como objetivo estimar el ingreso de una persona en base a
sus características utilizando modelos de Machine Learning supervisado
para regresión.

Se utilizarán múltiples nóminas públicas de instituciones del Estado para:
1. Unificar la data
2. Limpiar y preparar los datos
3. Realizar análisis exploratorio (EDA)
4. Entrenar distintos modelos de regresión
5. Evaluar métricas
6. Seleccionar el mejor modelo
7. Permitir predicciones con nuevos datos

Librerías utilizadas:
- pandas
- numpy
- matplotlib
- seaborn
- scikit-learn

1. Instalación de librerías
"""

!pip install openpyxl scikit-learn seaborn

"""2. Importación de librerías"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression, Ridge, BayesianRidge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

import warnings
warnings.filterwarnings("ignore")

"""Recolección de la Data"""

files = {
    "servicio nacional de salud.xlsx": 3,
    "dirección de recursos humanos.xlsx": 4,
    "superintendencia de bancos.xlsx": 4,
    "tesoreria nacional.xlsx": 4,
    "industria comercio y mypines.xlsx": 4
}

datasets = []

for file in files:
    df_raw = pd.read_excel(file, header=None)

    # buscar fila donde empieza la tabla real
    header_row = df_raw[df_raw.apply(lambda row: row.astype(str).str.contains("Nombre|NOMBRE|NOMBRES").any(), axis=1)].index[0]

    # cortar dataframe desde el header
    df = df_raw.iloc[header_row:].copy()

    # convertir esa fila en columnas
    df.columns = df.iloc[0]
    df = df.iloc[1:]

    # eliminar columnas vacías
    df = df.dropna(axis=1, how="all")

    df = df.reset_index(drop=True)
    df["institucion"] = file

    datasets.append(df)

print("Datasets cargados:", len(datasets))

"""Nominas Originales"""

for i, (file, df) in enumerate(zip(files.keys(), datasets)):
    print(f"\n===== NÓMINA {i+1} =====")
    print("Archivo:", file)
    print("Dimensiones:", df.shape)
    display(df.head())

"""Limpieza de datos"""

def limpiar_nomina(df):
    df = df.copy()

    # normalizar columnas
    df.columns = df.columns.astype(str).str.lower().str.strip()

    # eliminar filas basura (sin nombre)
    if 'nombre' in df.columns:
        df = df[df['nombre'].notna()]
    elif 'nombres' in df.columns:
        df = df[df['nombres'].notna()]

    # unificar nombre
    if 'nombres' in df.columns:
        df = df.rename(columns={'nombres': 'nombre'})

    # unificar genero
    if 'sexo' in df.columns:
        df = df.rename(columns={'sexo': 'genero'})

    # limpiar genero
    if 'genero' in df.columns:
        df['genero'] = df['genero'].astype(str).str.upper()
        df['genero'] = df['genero'].replace({
            'M': 'Masculino',
            'F': 'Femenino',
            'FEMENINO': 'Femenino',
            'MASCULINO': 'Masculino'
        })

    # detectar ingreso automáticamente
    posibles_ingresos = ['ingreso bruto', 'sueldo bruto', 'ingreso', 'total ing.', 'sueldo']

    col_ingreso = None
    for col in df.columns:
        for p in posibles_ingresos:
            if p in col:
                col_ingreso = col
                break
        if col_ingreso:
            break

    if col_ingreso is None:
        return pd.DataFrame()

    df = df.rename(columns={col_ingreso: 'ingreso'})

    # limpiar ingreso
    df['ingreso'] = df['ingreso'].astype(str).str.replace(',', '')
    df['ingreso'] = pd.to_numeric(df['ingreso'], errors='coerce')

    # unificar departamento
    if 'área de trabajo' in df.columns:
        df = df.rename(columns={'área de trabajo': 'departamento'})
    if 'direccion o departamento' in df.columns:
        df = df.rename(columns={'direccion o departamento': 'departamento'})

    # unificar cargo
    if 'puesto' in df.columns:
        df = df.rename(columns={'puesto': 'cargo'})

    # unificar categoria
    if 'estatus' in df.columns:
        df = df.rename(columns={'estatus': 'categoria servidor'})
    if 'tipo' in df.columns:
        df = df.rename(columns={'tipo': 'categoria servidor'})

    # eliminar nulos clave
    df = df.dropna(subset=['ingreso'])

    return df

"""Aplicar limpieza de datos"""

datasets_limpios = [limpiar_nomina(df) for df in datasets]
datasets_limpios = [df for df in datasets_limpios if not df.empty]

"""CONCATENACIÓN"""

df_total = pd.concat(datasets_limpios, ignore_index=True)

print("Filas totales:", df_total.shape)

"""Limpieza de Columnas basura"""

threshold = len(df_total) * 0.7
df_total = df_total.dropna(thresh=threshold, axis=1)

"""Selecciòn final"""

columnas_deseadas = [
    'nombre',
    'departamento',
    'cargo',
    'categoria servidor',
    'genero',
    'ingreso',
    'institucion'
]

columnas_existentes = [col for col in columnas_deseadas if col in df_total.columns]

df_total = df_total[columnas_existentes]

"""Feature Engineering"""

df_total["nombre_len"] = df_total["nombre"].astype(str).apply(len)
df_total["cargo_len"] = df_total["cargo"].astype(str).apply(len)

"""Tabla Ya limpia:"""

# ====== TABLA YA LIMPIA ======
print("===== DATASET FINAL LIMPIO =====")
print("Dimensiones:", df_total.shape)
display(df_total.head(10))

df_total['genero'].value_counts()

# @title

# ========== INGENIERÍA DE CARACTERÍSTICAS ==========

def extraer_nivel(cargo):
    """
    Extrae el nivel jerárquico del cargo basado en palabras clave.

    Parameters:
    cargo (str): Descripción del cargo

    Returns:
    int: Nivel jerárquico (1=operativo, 2=profesional, 3=mando medio, 4=alta dirección)
    """
    cargo_str = str(cargo).upper()

    # Alta dirección
    if any(palabra in cargo_str for palabra in [
        'MINISTRO', 'VICEMINISTRO', 'DIRECTOR', 'TESORERO',
        'SUPERINTENDENTE', 'GERENTE', 'PRESIDENTE', 'JEFE'
    ]):
        return 4

    # Mandos medios / supervisión
    elif any(palabra in cargo_str for palabra in [
        'COORDINADOR', 'JEFE', 'ENCARGADO', 'SUPERVISOR',
        'SUB', 'LIDER', 'ANALISTA SENIOR', 'ESPECIALISTA SENIOR'
    ]):
        return 3

    # Profesional / técnico
    elif any(palabra in cargo_str for palabra in [
        'ANALISTA', 'ESPECIALISTA', 'ASESOR', 'TECNICO',
        'ABOGADO', 'CONTADOR', 'INGENIERO', 'PROGRAMADOR',
        'ENFERMERO', 'MEDICO', 'PERIODISTA', 'DISEÑADOR'
    ]):
        return 2

    # Soporte / operativo
    else:
        return 1

def extraer_tipo_departamento(departamento):
    """
    Clasifica el tipo de departamento según su función principal.

    Parameters:
    departamento (str): Nombre del departamento

    Returns:
    int: Tipo de departamento (1=operativo, 2=soporte, 3=especializado, 4=dirección)
    """
    depto_str = str(departamento).upper()

    # Alta dirección / Despachos
    if any(palabra in depto_str for palabra in [
        'DESPACHO', 'GABINETE', 'PRESIDENCIA', 'SUPERINTENDENTE', 'VICEMINISTERIO'
    ]):
        return 4

    # Áreas legales / regulatorias
    elif any(palabra in depto_str for palabra in [
        'JURIDICO', 'LEGAL', 'CONSULTORIA', 'REGULACION', 'SANCIONES', 'CUMPLIMIENTO'
    ]):
        return 3

    # Áreas financieras / administrativas
    elif any(palabra in depto_str for palabra in [
        'FINANCIERO', 'TESORERIA', 'CONTABILIDAD', 'PRESUPUESTO',
        'ADMINISTRATIVO', 'COMPRAS', 'CONTRATACIONES'
    ]):
        return 3

    # Recursos Humanos / Talento
    elif any(palabra in depto_str for palabra in [
        'RECURSOS HUMANOS', 'TALENTO', 'PERSONAL', 'GESTION HUMANA', 'NOMINA'
    ]):
        return 2

    # Tecnología / Sistemas
    elif any(palabra in depto_str for palabra in [
        'TECNOLOGIA', 'SISTEMAS', 'INFORMATICA', 'TIC', 'DATOS'
    ]):
        return 2

    # Áreas operativas / servicios generales
    else:
        return 1

# Aplicar las funciones para crear nuevas características
df_total['nivel_jerarquico'] = df_total['cargo'].apply(extraer_nivel)
df_total['tipo_departamento'] = df_total['departamento'].apply(extraer_tipo_departamento)  # ← Línea corregida

print(f"\n✅ Nuevas características añadidas:")
print(f"   - nivel_jerarquico (entero, rango 1-4)")
print(f"   - tipo_departamento (entero, rango 1-4)")
print(f"\nTotal de columnas ahora: {df_total.shape[1]}")
print(f"Columnas disponibles: {df_total.columns.tolist()}")

# Verificar la distribución de los nuevos campos
print("\n=== DISTRIBUCIÓN DE NIVEL JERÁRQUICO ===")
print(df_total['nivel_jerarquico'].value_counts().sort_index())

print("\n=== DISTRIBUCIÓN DE TIPO DEPARTAMENTO ===")
print(df_total['tipo_departamento'].value_counts().sort_index())

"""EDA"""

# INFO GENERAL
df_total.info()

# NULOS
df_total.isnull().sum()

# ESTADÍSTICAS
df_total.describe()

# HISTOGRAMA
import matplotlib.pyplot as plt
plt.hist(df_total["ingreso"], bins=50)
plt.title("Distribución del ingreso")
plt.show()

# INGRESO POR GENERO
df_total.groupby("genero")["ingreso"].mean().plot(kind="bar")
plt.title("Ingreso promedio por género")
plt.show()

# INGRESO POR INSTITUCION
df_total.groupby("institucion")["ingreso"].mean().plot(kind="bar")
plt.title("Ingreso promedio por institución")
plt.xticks(rotation=90)
plt.show()

# CORRELACION
import seaborn as sns
sns.heatmap(df_total.corr(numeric_only=True), annot=True)
plt.show()

"""Interpretacion:

Se observa que los ingresos presentan una alta variabilidad, con presencia de valores altos correspondientes a cargos jerárquicos.

Además, los ingresos promedio varían según el género y el cargo, lo cual indica una posible relación entre estas variables.

Validaciòn final
"""

df_total.info()
df_total.isnull().sum()
df_total.describe()

"""X e y"""

# ========== DEFINICIÓN DE X e y ==========
# Seleccionamos 6 características
columnas_caracteristicas = [
    'departamento',      # categórica
    'cargo',            # categórica
    'genero',           # categórica
    'institucion',      # categórica
    'nivel_jerarquico', # entero (nueva feature)
    'tipo_departamento' # entero (nueva feature)
]

X = df_total[columnas_caracteristicas]
y = df_total["ingreso"]

print(f"\n✅ Características de entrada: {len(X.columns)}")
for col in X.columns:
    dtype = X[col].dtype
    tipo = "categórica" if dtype == 'object' else "entero" if dtype in ['int64', 'int32'] else "decimal"
    print(f"   - {col}: {tipo}")
print(f"\n✅ Etiqueta de salida: ingreso (tipo real)")

# Verificar que no hay valores nulos en las nuevas columnas
print(f"\n✅ Verificación de nulos:")
print(f"   nivel_jerarquico: {df_total['nivel_jerarquico'].isnull().sum()} nulos")
print(f"   tipo_departamento: {df_total['tipo_departamento'].isnull().sum()} nulos")

"""Encoding"""

from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

"""Scaling"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""Train/test"""

from sklearn.model_selection import train_test_split
import numpy as np

# Dividir los datos primero
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# APLICAR TRANSFORMACIÓN LOGARÍTMICA a los datos de entrenamiento y prueba
y_train_log = np.log1p(y_train)
y_test_log = np.log1p(y_test)

"""Modelos

"""

from sklearn.linear_model import LinearRegression, Ridge, Lasso, BayesianRidge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

modelos = {
    "OLS": LinearRegression(),
    "Ridge": Ridge(),
    "Bayesian": BayesianRidge(),
    "Lasso": Lasso(),
    "KNN": KNeighborsRegressor(),
    "Tree": DecisionTreeRegressor(),
    "RandomForest": RandomForestRegressor(),
    "SVR": SVR(),
    "MLP": MLPRegressor(max_iter=500),
    "AdaBoost": AdaBoostRegressor()
}

X_train

"""EVALUACIÓN"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

resultados = []

for nombre, modelo in modelos.items():
    # Entrenar con los datos transformados (log)
    modelo.fit(X_train, y_train_log)

    # Predecir en escala logarítmica
    pred_log = modelo.predict(X_test)

    # deshacer la transformación para obtener predicciones en escala original
    # expm1 es la inversa de log1p: expm1(x) = e^x - 1
    pred = np.expm1(pred_log)

    # Calcular métricas con los valores ORIGINALES
    rmse = np.sqrt(mean_squared_error(y_test, pred))

    resultados.append({
        "Modelo": nombre,
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": rmse,
        "R2": r2_score(y_test, pred)
    })

df_resultados = pd.DataFrame(resultados)
df_resultados.sort_values("R2", ascending=False)

"""El modelo Random Forest presentó el mejor desempeño, logrando el mayor R², lo que indica una mejor capacidad de predicción del ingreso en comparación con los demás modelos.

IMPORTANCIA DE VARIABLES
"""

# @title
import pandas as pd

importancias = modelos["RandomForest"].feature_importances_
pd.Series(importancias, index=X.columns).sort_values(ascending=False)

"""PREDICCIÓN CON CSV"""

# @title
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder, StandardScaler
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# PRIMERO: ENTRENAR EL MODELO
# ============================================================

print("=" * 60)
print(" ENTRENANDO MODELO")
print("=" * 60)

# Datos de entrenamiento
datos_ejemplo = pd.DataFrame({
    'cargo': ['CONSERJE', 'ENFERMERO', 'DIRECTOR', 'ANALISTA', 'SECRETARIA',
              'AUXILIAR', 'JEFE', 'INGENIERO', 'CONTADOR', 'MEDICO'],
    'departamento': ['MANTENIMIENTO', 'SALUD', 'DIRECCION', 'FINANZAS', 'ADMINISTRACION',
                     'MANTENIMIENTO', 'OPERACIONES', 'TECNOLOGIA', 'FINANZAS', 'SALUD'],
    'genero': ['M', 'F', 'M', 'F', 'F', 'M', 'M', 'M', 'F', 'F'],
    'institucion': ['MINSA', 'MINSA', 'MINSA', 'BANCO', 'BANCO', 'MINSA', 'BANCO', 'TELECOM', 'BANCO', 'MINSA'],
    'ingreso': [15000, 45000, 85000, 35000, 28000, 18000, 65000, 55000, 48000, 72000]
})

# Funciones de feature engineering
def extraer_nivel(cargo):
    cargo_str = str(cargo).upper()
    if any(p in cargo_str for p in ['DIRECTOR', 'JEFE', 'GERENTE', 'PRESIDENTE']):
        return 4
    elif any(p in cargo_str for p in ['COORDINADOR', 'ENCARGADO', 'SUPERVISOR']):
        return 3
    elif any(p in cargo_str for p in ['ANALISTA', 'INGENIERO', 'MEDICO', 'ENFERMERO', 'CONTADOR']):
        return 2
    else:
        return 1

def extraer_tipo_departamento(departamento):
    depto_str = str(departamento).upper()
    if any(p in depto_str for p in ['DIRECCION', 'DESPACHO', 'GERENCIA']):
        return 4
    elif any(p in depto_str for p in ['FINANZAS', 'CONTABILIDAD', 'JURIDICO']):
        return 3
    elif any(p in depto_str for p in ['ADMINISTRACION', 'TECNOLOGIA', 'RRHH']):
        return 2
    else:
        return 1

# Aplicar feature engineering
datos_ejemplo['nivel_jerarquico'] = datos_ejemplo['cargo'].apply(extraer_nivel)
datos_ejemplo['tipo_departamento'] = datos_ejemplo['departamento'].apply(extraer_tipo_departamento)

# Codificar
encoders = {}
df_train = datos_ejemplo.copy()
for col in ['cargo', 'departamento', 'genero', 'institucion']:
    le = LabelEncoder()
    df_train[col] = le.fit_transform(df_train[col])
    encoders[col] = le

# Definir EL ORDEN EXACTO de las columnas (¡esto es clave!)
feature_cols = ['cargo', 'departamento', 'genero', 'institucion',
                'nivel_jerarquico', 'tipo_departamento']

X_train = df_train[feature_cols]
y_train = df_train['ingreso']

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

modelo = RandomForestRegressor(n_estimators=100, random_state=42)
modelo.fit(X_train_scaled, y_train)

print("✅ Modelo entrenado con éxito!\n")

# ============================================================
# FUNCIÓN CORREGIDA - MANTIENE EL MISMO ORDEN DE COLUMNAS
# ============================================================

def predecir_nuevo(csv_path):
    """
    Predice los ingresos para nuevos datos desde un archivo CSV.
    """
    print(f"\n Leyendo archivo: {csv_path}")
    nuevo = pd.read_csv(csv_path)
    print(f"   {len(nuevo)} empleados encontrados")

    # Aplicar ingeniería de características
    nuevo['nivel_jerarquico'] = nuevo['cargo'].apply(extraer_nivel)
    nuevo['tipo_departamento'] = nuevo['departamento'].apply(extraer_tipo_departamento)

    # Codificar variables categóricas
    for col in ['cargo', 'departamento', 'genero', 'institucion']:
        le = encoders[col]
        nuevo[col] = nuevo[col].astype(str).apply(
            lambda x: le.transform([x])[0] if x in le.classes_ else -1
        )

    # 🔴 CLAVE: Usar EXACTAMENTE el mismo orden de columnas que en entrenamiento
    # Esto asegura que las columnas estén en el orden correcto
    X_nuevo = nuevo[feature_cols]  # Mismo orden que en entrenamiento

    # Escalar
    X_nuevo_scaled = scaler.transform(X_nuevo)

    # Predecir
    predicciones = modelo.predict(X_nuevo_scaled)

    # Crear resultado con columnas originales
    resultado_original = pd.read_csv(csv_path)
    resultado = resultado_original.copy()
    resultado['ingreso_predicho'] = predicciones
    resultado['ingreso_formateado'] = resultado['ingreso_predicho'].apply(lambda x: f"RD$ {x:,.2f}")

    return resultado

# ============================================================
# EJECUTAR PREDICCIONES
# ============================================================

print("=" * 60)
print(" EJECUTANDO PREDICCIONES")
print("=" * 60)

# Crear archivo de ejemplo
csv_ejemplo = pd.DataFrame({
    'cargo': ['ANALISTA', 'JEFE', 'INGENIERO', 'SECRETARIA', 'CONSERJE'],
    'departamento': ['FINANZAS', 'OPERACIONES', 'TECNOLOGIA', 'ADMINISTRACION', 'MANTENIMIENTO'],
    'genero': ['M', 'F', 'M', 'F', 'M'],
    'institucion': ['BANCO', 'BANCO', 'TELECOM', 'MINSA', 'MINSA']
})
csv_ejemplo.to_csv('empleados_nuevos.csv', index=False)
print("\n✅ Archivo de ejemplo creado: 'empleados_nuevos.csv'")
print("\n📋 Contenido del archivo:")
print(csv_ejemplo)

# 🔴 LLAMAR A LA FUNCIÓN
resultados = predecir_nuevo('empleados_nuevos.csv')

# ============================================================
# MOSTRAR RESULTADOS
# ============================================================

print("\n" + "=" * 60)
print("💰 RESULTADOS DE PREDICCIÓN")
print("=" * 60)
print("\n📋 Tabla completa:")
print(resultados.to_string(index=False))

print("\n📊 Resumen por empleado:")
print("-" * 70)
for i, row in resultados.iterrows():
    print(f"{row['cargo']:12s} | {row['departamento']:15s} | {row['institucion']:8s} | {row['ingreso_formateado']}")

# Estadísticas
print("\n📈 ESTADÍSTICAS:")
print(f"   Total predicciones: {len(resultados)}")
print(f"   Ingreso promedio: RD$ {resultados['ingreso_predicho'].mean():,.2f}")
print(f"   Ingreso mínimo: RD$ {resultados['ingreso_predicho'].min():,.2f}")
print(f"   Ingreso máximo: RD$ {resultados['ingreso_predicho'].max():,.2f}")

# Guardar resultados
resultados.to_csv('resultados_finales.csv', index=False)
print("\n💾 Resultados guardados en 'resultados_finales.csv'")

print("\n" + "=" * 60)
print("🏁 PREDICCIÓN COMPLETADA")
print("=" * 60)

# ============================================================
# CÓMO USAR CON TU PROPIO CSV
# ============================================================
print("\n" + "=" * 60)
print("💡 CÓMO USAR CON TU PROPIO CSV")
print("=" * 60)
print("""
1. Tu archivo CSV debe tener estas columnas:
   - cargo
   - departamento
   - genero
   - institucion

2. Ejecuta esta línea (cambia 'tu_archivo.csv'):
   >>> resultados = predecir_nuevo('tu_archivo.csv')
   >>> print(resultados)
""")

"""## Conclusiones

El modelo Random Forest obtuvo el mejor rendimiento con un R² superior, lo que indica que el ingreso depende de relaciones no lineales entre las variables.

Se observó que variables como el cargo, la institución y características derivadas influyen significativamente en la predicción del ingreso.

El pipeline implementado permite procesar nuevos datos y generar predicciones de manera consistente.
"""